server:
  port: 8080
spring:
  application:
    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456
  main:
    allow-bean-definition-overriding: true #开启bean定义覆盖
  redis:
    host: 你的redis服务器
    port: 6379
    database: 0
    password: 你的redis密码
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存过期时间
  shardingsphere: #使用读写分离需要用的shardingsphere
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://你的数据库ip:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 你的数据库密码
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.123.185:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 你的密码
    masterslave:

      # 读写分离配置
      load-balance-algorithm-type: round_robin #负载均衡使用轮询
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示（在控制台显示SQL语句），默认false

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
#    mybatis输出日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path:  D:/teaImg/
